// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAliXMa3OZHI9QsaMo-hXoIDrvuQ0TtzB8',
    appId: '1:448966879427:web:1a43c6c984faacb2dd1a76',
    messagingSenderId: '448966879427',
    projectId: 'optigasto',
    authDomain: 'optigasto.firebaseapp.com',
    storageBucket: 'optigasto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAliXMa3OZHI9QsaMo-hXoIDrvuQ0TtzB8',
    appId: '1:448966879427:android:1a43c6c984faacb2dd1a76',
    messagingSenderId: '448966879427',
    projectId: 'optigasto',
    storageBucket: 'optigasto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivmdFPgWNnMAvzBv9VO9e7CXjkc2_9zg',
    appId: '1:448966879427:ios:64557dbefaf7970ddd1a76',
    messagingSenderId: '448966879427',
    projectId: 'optigasto',
    storageBucket: 'optigasto.firebasestorage.app',
    iosBundleId: 'com.optigasto.optigasto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivmdFPgWNnMAvzBv9VO9e7CXjkc2_9zg',
    appId: '1:448966879427:ios:64557dbefaf7970ddd1a76',
    messagingSenderId: '448966879427',
    projectId: 'optigasto',
    storageBucket: 'optigasto.firebasestorage.app',
    iosBundleId: 'com.optigasto.optigasto',
  );
}

// Made with Bob
